/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/paginated-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    limit: number;
                    cursor?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items?: number[];
                            nextPage?: number;
                        };
                    };
                };
                /** @description Error response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            code?: number;
                            message?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["CreateReply"];
            responses: {
                201: components["responses"]["CreateReply"];
                500: components["responses"]["Error"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blogposts/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    version?: number;
                    format?: string;
                };
                header?: never;
                path: {
                    post_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["PostGet"];
                404: components["responses"]["Error"];
                500: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    post_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["PostDelete"];
                500: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    post_id: string;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["PatchPost"];
            responses: {
                200: components["responses"]["PatchPost"];
                404: components["responses"]["Error"];
                500: components["responses"]["Error"];
            };
        };
        trace?: never;
    };
    "/string-array": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["StringArray"];
                500: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Post: {
            title: string;
            body: string;
            publish_date?: number;
        };
        StringArray: string[];
    };
    responses: {
        /** @description CreateReply response */
        CreateReply: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json;charset=utf-8": {
                    message: string;
                };
            };
        };
        /** @description Error response */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    code: number;
                    message: string;
                };
            };
        };
        /** @description PostGet response */
        PostGet: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Post"];
            };
        };
        /** @description PatchPost response */
        PatchPost: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    status: string;
                };
            };
        };
        /** @description PostDelete response */
        PostDelete: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    status: string;
                };
            };
        };
        /** @description StringArray response */
        StringArray: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["StringArray"];
            };
        };
    };
    parameters: never;
    requestBodies: {
        CreateReply: {
            content: {
                "application/json;charset=utf-8": {
                    message: string;
                    replied_at: number;
                };
            };
        };
        PatchPost: {
            content: {
                "application/json": {
                    title?: string;
                    body?: string;
                    publish_date?: number;
                };
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type operations = Record<string, never>;
