/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type $Read<T> = {
    readonly $read: T;
};
export type $Write<T> = {
    readonly $write: T;
};
type IsMarker<T, Marker> = [
    NonNullable<T>
] extends [
    never
] ? false : NonNullable<T> extends Marker ? true : false;
type Scalar = string | number | boolean | bigint | symbol | null | undefined;
type Callable = (...args: never[]) => unknown;
export type Readable<T> = T extends $Write<unknown> ? never : T extends $Read<infer U> ? Readable<U> : T extends Scalar | Callable ? T : T extends readonly unknown[] ? {
    [K in keyof T]: Readable<T[K]>;
} : T extends object ? {
    [K in keyof T as IsMarker<T[K], $Write<unknown>> extends true ? never : K]: Readable<T[K]>;
} : T;
export type Writable<T> = T extends $Read<unknown> ? never : T extends $Write<infer U> ? Writable<U> : T extends Scalar | Callable ? T : T extends readonly unknown[] ? {
    [K in keyof T]: Writable<T[K]>;
} : T extends object ? {
    [K in keyof T as IsMarker<T[K], $Read<unknown>> extends true ? never : K]: Writable<T[K]>;
} & {
    [K in keyof T as IsMarker<T[K], $Read<unknown>> extends true ? K : never]?: never;
} : T;
export interface paths {
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Resource"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            id?: $Read<number>;
            name: string;
            password?: $Write<string>;
        };
        Resource: {
            id: number;
            items: components["schemas"]["ResourceItem"][];
        };
        ResourceItem: {
            id: number;
            nested: $Read<components["schemas"]["NestedObject"]>;
        };
        NestedObject: {
            entries: $Read<components["schemas"]["Entry"][]>;
        };
        Entry: {
            code: string;
            label: $Read<string>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type operations = Record<string, never>;
