name: release

on:
  push:
    branches:
      - main

permissions:
  id-token: write # Required for OIDC
  contents: write
  pull-requests: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Git setup
        uses: actions/checkout@v6

      - uses: ./.github/actions/setup

      - name: Build all packages
        run: pnpm run build

      - name: Changesets version and/or publish
        uses: changesets/action@v1
        with:
          version: pnpm run version
          publish: pnpm exec changeset publish
          commit: "[ci] release"
          title: "[ci] release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
