name: release

on:
  workflow_call:

permissions:
  id-token: write # Required for OIDC
  contents: write
  pull-requests: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Git setup
        uses: actions/checkout@v6

      - uses: ./.github/actions/setup

      - name: Build all packages
        run: pnpm run build

      - name: Changesets version and/or publish
        uses: changesets/action@v2.1.2
        with:
          version-script: pnpm run version
          publish-script: pnpm exec changeset publish
          commit-message: "chore(release): version packages"
          pr-title: "release: publish package updates"
